package network

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const caddyConfigDir = "/etc/caddy"
const caddyConfigFile = caddyConfigDir + "/Caddyfile"

func SetupCaddy(domainSuffix string) error {
	if _, err := exec.LookPath("caddy"); err != nil {
		return fmt.Errorf("caddy not found. Install with: apt-get install caddy")
	}

	config := fmt.Sprintf(`# Auto-generated by TAVPBox
# Global options
{
    auto_https disable
}

# Default: respond to any unmatched requests
:80 {
    respond "TAVPBox: no box found for this domain" 404
}
`)
	os.MkdirAll(caddyConfigDir, 0755)
	os.WriteFile(caddyConfigFile, []byte(config), 0644)

	return restartCaddy()
}

func AddCaddyRoute(domain, containerIP string, port int) error {
	data, _ := os.ReadFile(caddyConfigFile)
	config := string(data)

	route := fmt.Sprintf(`
%s {
    reverse_proxy %s:%d
}
`, domain, containerIP, port)

	config = strings.TrimSuffix(config, ":80 {")
	config += route
	config += ":80 {\n"

	return os.WriteFile(caddyConfigFile, []byte(config), 0644)
}

func RemoveCaddyRoute(domain string) error {
	data, _ := os.ReadFile(caddyConfigFile)
	config := string(data)

	blocks := splitCaddyBlocks(config)
	var newBlocks []string
	for _, block := range blocks {
		if !strings.Contains(block, domain) {
			newBlocks = append(newBlocks, block)
		}
	}

	return os.WriteFile(caddyConfigFile, []byte(strings.Join(newBlocks, "\n")), 0644)
}

func splitCaddyBlocks(config string) []string {
	var blocks []string
	depth := 0
	current := ""

	for _, line := range strings.Split(config, "\n") {
		current += line + "\n"
		depth += strings.Count(line, "{") - strings.Count(line, "}")
		if depth == 0 && strings.TrimSpace(current) != "" {
			blocks = append(blocks, current)
			current = ""
		}
	}
	if strings.TrimSpace(current) != "" {
		blocks = append(blocks, current)
	}
	return blocks
}

func restartCaddy() error {
	if err := exec.Command("systemctl", "restart", "caddy").Run(); err != nil {
		return exec.Command("caddy", "reload", "--config", caddyConfigFile).Run()
	}
	return nil
}
