FROM node:20-alpine

LABEL org.opencontainers.image.source="https://github.com/tavp-stack/tavpbox"
LABEL org.opencontainers.image.description="TAVPBox Node.js base image with Nginx"

ENV TZ=Asia/Jakarta

RUN apk add --no-cache nginx curl tzdata

COPY nginx.conf /etc/nginx/http.d/default.conf
COPY start.sh /usr/local/bin/tavpbox-start.sh
RUN chmod +x /usr/local/bin/tavpbox-start.sh

CMD ["/usr/local/bin/tavpbox-start.sh"]
